# 0 IMPORTS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1 Loading the dataset

In [3]:
file_path = '/content/data.csv'
df = pd.read_csv(file_path)
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
# drop last column (extra column added by pd)
# and unnecessary first column (id)
df.drop(df.columns[[-1, 0]], axis=1, inplace=True)

In [6]:
# 'diagnosis' is class label(target) B for benign and M for malignant
# let us observe the distribution of class label
df.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

Let us understand feature columns. `df.describe()` function fetches you descriptive statistics that summarize the central tendency, dispersion and shape of a dataset's distribution, excluding NaN values.

In [7]:
df.describe()

       radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In above statistical description, we can observe the values across feature columns fall in varying scale. Normalization is one of the many feature engineering techniques that we are going to use. Normalization is the process of converting a range of values, into a standard range of values, typically in the interval [−1, 1] or [0, 1].

In [8]:
from sklearn.preprocessing import MinMaxScaler

Y = df.loc[:,'diagnosis']
X = df.iloc[:,1:]

X_normalized = MinMaxScaler().fit_transform(X)
X = pd.DataFrame(X_normalized)